CREATE DATABASE game_guide_eso_database;
\c game_guide_eso_database

CREATE TABLE guides(
    id SERIAL PRIMARY KEY,
    guide_title TEXT,
    class_name TEXT,
    role_name TEXT,
    guide_description TEXT,
    character_race_suggestion TEXT,
    head_set_name TEXT,
    head_armor_weight TEXT,
    head_enchantment TEXT,
    head_trait TEXT,
    head_where_to_obtain TEXT,
    shoulder_set_name TEXT,
    shoulder_armor_weight TEXT,
    shoulder_enchantment TEXT,
    shoulder_trait TEXT,
    shoulder_where_to_obtain TEXT,
    body_set_name TEXT,
    body_armor_weight TEXT,
    body_enchantment TEXT,
    body_trait TEXT,
    body_where_to_obtain TEXT,
    hand_set_name TEXT,
    hand_armor_weight TEXT,
    hand_enchantment TEXT,
    hand_trait TEXT,
    hand_where_to_obtain TEXT,
    belt_set_name TEXT,
    belt_armor_weight TEXT,
    belt_enchantment TEXT,
    belt_trait TEXT,
    belt_where_to_obtain TEXT,
    leg_set_name TEXT,
    leg_armor_weight TEXT,
    leg_enchantment TEXT,
    leg_trait TEXT,
    leg_where_to_obtain TEXT,
    boots_set_name TEXT,
    boots_armor_weight TEXT,
    boots_enchantment TEXT,
    boots_trait TEXT,
    boots_where_to_obtain TEXT,
    necklace_set_name TEXT,
    necklace_enchantment TEXT,
    necklace_trait TEXT,
    necklace_where_to_obtain TEXT,
    ring_1_set_name TEXT,
    ring_1_enchantment TEXT,
    ring_1_trait TEXT,
    ring_1_where_to_obtain TEXT,
    ring_2_set_name TEXT,
    ring_2_enchantment TEXT,
    ring_2_trait TEXT,
    ring_2_where_to_obtain TEXT,
    primary_mainhand_set_name TEXT,
    primary_mainhand_weapon_type TEXT,
    primary_mainhand_enchantment TEXT,
    primary_mainhand_trait TEXT,
    primary_mainhand_where_to_obtain TEXT,
    primary_offhand_set_name TEXT,
    primary_offhand_weapon_type TEXT,
    primary_offhand_enchantment TEXT,
    primary_offhand_trait TEXT,
    primary_offhand_where_to_obtain TEXT,
    secondary_mainhand_set_name TEXT,
    secondary_mainhand_weapon_type TEXT,
    secondary_mainhand_enchantment TEXT,
    secondary_mainhand_trait TEXT,
    secondary_mainhand_where_to_obtain TEXT,
    secondary_offhand_set_name TEXT,
    secondary_offhand_weapon_type TEXT,
    secondary_offhand_enchantment TEXT,
    secondary_offhand_trait TEXT,
    secondary_offhand_where_to_obtain TEXT,
    skill_primary_1 TEXT,
    skill_primary_2 TEXT,
    skill_primary_3 TEXT,
    skill_primary_4 TEXT,
    skill_primary_5 TEXT,
    skill_primary_ultimate TEXT,
    skill_secondary_1 TEXT,
    skill_secondary_2 TEXT,
    skill_secondary_3 TEXT,
    skill_secondary_4 TEXT,
    skill_secondary_5 TEXT,
    skill_secondary_ultimate TEXT,
    attributes_health TEXT,
    attributes_stamina TEXT,
    attributes_magicka TEXT,
    cp_blue_slottable_1 TEXT,
    cp_blue_slottable_2 TEXT,
    cp_blue_slottable_3 TEXT,
    cp_blue_slottable_4 TEXT,
    cp_red_slottable_1 TEXT,
    cp_red_slottable_2 TEXT,
    cp_red_slottable_3 TEXT,
    cp_red_slottable_4 TEXT,
    cp_green_slottable_1 TEXT,
    cp_green_slottable_2 TEXT,
    cp_green_slottable_3 TEXT,
    cp_green_slottable_4 TEXT,
    consumable_food TEXT,
    consumable_potion TEXT,
    mundus_stone TEXT,
    likes INTEGER
);

CREATE TABLE comments(
    id SERIAL PRIMARY KEY,
    guide_id INTEGER,
    comment TEXT
);

INSERT INTO guides(
    guide_title,
    class_name,
    role_name,
    guide_description,
    character_race_suggestion,
    head_set_name,
    head_armor_weight,
    head_enchantment,
    head_trait,
    head_where_to_obtain,
    shoulder_set_name,
    shoulder_armor_weight,
    shoulder_enchantment,
    shoulder_trait,
    shoulder_where_to_obtain,
    body_set_name,
    body_armor_weight,
    body_enchantment,
    body_trait,
    body_where_to_obtain,
    hand_set_name,
    hand_armor_weight,
    hand_enchantment,
    hand_trait,
    hand_where_to_obtain,
    belt_set_name,
    belt_armor_weight,
    belt_enchantment,
    belt_trait,
    belt_where_to_obtain,
    leg_set_name,
    leg_armor_weight,
    leg_enchantment,
    leg_trait,
    leg_where_to_obtain,
    boots_set_name,
    boots_armor_weight,
    boots_enchantment,
    boots_trait,
    boots_where_to_obtain,
    necklace_set_name,
    necklace_enchantment,
    necklace_trait,
    necklace_where_to_obtain,
    ring_1_set_name,
    ring_1_enchantment,
    ring_1_trait,
    ring_1_where_to_obtain,
    ring_2_set_name,
    ring_2_enchantment,
    ring_2_trait,
    ring_2_where_to_obtain,
    primary_mainhand_set_name,
    primary_mainhand_weapon_type,
    primary_mainhand_enchantment,
    primary_mainhand_trait,
    primary_mainhand_where_to_obtain,
    primary_offhand_set_name,
    primary_offhand_weapon_type,
    primary_offhand_enchantment,
    primary_offhand_trait,
    primary_offhand_where_to_obtain,
    secondary_mainhand_set_name,
    secondary_mainhand_weapon_type,
    secondary_mainhand_enchantment,
    secondary_mainhand_trait,
    secondary_mainhand_where_to_obtain,
    secondary_offhand_set_name,
    secondary_offhand_weapon_type,
    secondary_offhand_enchantment,
    secondary_offhand_trait,
    secondary_offhand_where_to_obtain,
    skill_primary_1,
    skill_primary_2,
    skill_primary_3,
    skill_primary_4,
    skill_primary_5,
    skill_primary_ultimate,
    skill_secondary_1,
    skill_secondary_2,
    skill_secondary_3,
    skill_secondary_4,
    skill_secondary_5,
    skill_secondary_ultimate,
    attributes_health,
    attributes_stamina,
    attributes_magicka,
    cp_blue_slottable_1,
    cp_blue_slottable_2,
    cp_blue_slottable_3,
    cp_blue_slottable_4,
    cp_red_slottable_1,
    cp_red_slottable_2,
    cp_red_slottable_3,
    cp_red_slottable_4,
    cp_green_slottable_1,
    cp_green_slottable_2,
    cp_green_slottable_3,
    cp_green_slottable_4,
    consumable_food,
    consumable_potion,
    mundus_stone,
    likes
)
VALUES
    ('The Immortal', 'Necromancer', 'Tank', 'A build for tanks who like to sit in the middle of everything, take no damage and have almost unending amounts of healing and resource sustain', 'Nord', 'Thurvokun', 'Heavy', 'Health', 'Sturdy', 'Fang Lair', 'Thurvokun', 'Heavy', 'Health', 'Sturdy', 'Undaunted Merchant Box', 'Bloodlords Embrace', 'Heavy', 'Health', 'Sturdy', 'Scrying', 'Yolnahkriin', 'Heavy', 'Health', 'Sturdy', 'Sunspire', 'Yolnahkriin', 'Heavy', 'Health', 'Sturdy', 'Sunspire', 'Yolnahkriin', 'Heavy', 'Health', 'Sturdy', 'Sunspire', 'Yolnahkriin', 'Heavy', 'Health', 'Sturdy', 'Sunspire', 'Crimson Oath', 'Reduce Block Cost', 'Healthy', 'The Dread Cellar', 'Crimson Oath', 'Reduce Block Cost', 'Healthy', 'The Dread Cellar', 'Crimson Oath', 'Reduce Block Cost', 'Healthy', 'The Dread Cellar', 'Yolnahkriin', 'Any 1h', 'absorb stamina', 'Defending', 'Sunspire', 'Crimson Oath', 'Shield', 'Health', 'Sturdy', 'The Dread Cellar', 'Crimson Oath', 'Ice Staff', 'Crushing', 'Infused', 'The Dread Cellar', '', '', '', '', '', 'Defensive Stance', 'Hungry Scythe', 'Ransack', 'Expunge And Modify', 'Deaden Pain', 'Glacial Colossus', 'Spirit Guardian', 'Mortal Coil', 'Inner Rage', 'Elemental Blockade', 'Beckoning Armor', 'Renewing Animation', '64', '0', '0', 'Duelists Rebuff', 'Enduring Resolve', 'Unassailable', 'Ironclad', 'Boundless Vitality', 'Fortified', 'Bracing Anchor', 'Slippery', 'Treasure Hunter', 'Rationer', 'Liquid Efficiency', 'Professional Upkeep', 'Bewitched Sugar Skulls', 'Any Tri Stat Potion', 'The Lord', 0);


INSERT INTO comments(guide_id, comment) 
VALUES
    (1, 'I use this build and never felt tankier');